openapi: 3.0.0
info:
  title: API Générateur de Roadmap
  version: 1.0.0

paths:
  /process_prompt:
    post:
      operationId: process_prompt
      summary: Traitement d'un nouveau projet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
              required:
                - prompt
      responses:
        '200':
          description: Projet traité avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  task:
                    type: object
        '400':
          description: Requête invalide
        '500':
          description: Erreur interne du serveur
